
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmEFpI8EV7ZgZiSNHvntSHjXhD0jiTIxk',
    iosBundleId: 'act5.com',
    appId: '1:607675576320:ios:0d5cbad1d95eb0307228e5',
    storageBucket: 'act5-flutlab.appspot.com',
    messagingSenderId: '607675576320',
    iosClientId: 'undefined',
    projectId: 'act5-flutlab'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVNiaBCWOZFRLHRZf-sc-J9Gl57UNYlNI',
    appId: '1:607675576320:android:385a19d4131c5dcd7228e5',
    messagingSenderId: '607675576320',
    projectId: 'act5-flutlab',
    storageBucket: 'act5-flutlab.appspot.com'
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvUbWI7CD6Az-9CllnEbpps2pENVEDrbs',
    authDomain: 'act5-flutlab.firebaseapp.com',
    projectId: 'act5-flutlab',
    storageBucket: 'act5-flutlab.appspot.com',
    messagingSenderId: '607675576320',
    appId: '1:607675576320:web:e566694d77dc7d1b7228e5'
  );
}
